package com.example.tiptracker.ui.logs

import java.time.LocalDate
import kotlin.math.ceil
import kotlin.math.roundToInt

data class LogFormState(
    val id: Int = 0, // auto generated by db
    val bill: String = "",
    val tipPercent: String = "",
    val partySize: String = "",
    val roundUpTip: Boolean = false,
    val roundUpTotal: Boolean = false,
    val restaurantName: String = "",
    val restaurantDescription: String = "",
    val date: LocalDate = LocalDate.now(),
    val isSaving: Boolean = false
) {
    val parsedBill: Double get() = bill.toDoubleOrNull() ?: 0.0
    val parsedTipPercent: Double get() = tipPercent.toDoubleOrNull() ?: 0.0
    val parsedPartySize: Int get() = partySize.toIntOrNull()?.coerceAtLeast(1) ?: 1

    // Adjusts tip amount based on rounding preferences
    val calculatedTip: Double
        get() {
            var tip = parsedBill * (parsedTipPercent / 100)
            if (roundUpTip) {
                tip = ceil(tip)
            } else if (roundUpTotal) {
                val total = parsedBill + tip
                val roundedTotal = ceil(total)
                tip = tip + roundedTotal - total
            }
            val roundedTip = (tip * 100).roundToInt() / 100.0
            return roundedTip
        }

    val calculatedTotal: Double get() {
        val total = parsedBill + calculatedTip
        val roundedTotal = (total * 100).roundToInt() / 100.0
        return roundedTotal
    }

    val calculatedPerPerson: Double get() {
        val perPerson = calculatedTotal / parsedPartySize
        val roundedPerPerson = (perPerson * 100).roundToInt() / 100.0
        return roundedPerPerson
    }

    // Adjusts tip percent based on rounded tip amount 
    val trueTipPercent: Double get() {
        if ((roundUpTip || roundUpTotal) && parsedBill > 0.0) {
            val tipPercent =  (calculatedTip / parsedBill) * 100
            val roundedTipPercent = (tipPercent * 100).roundToInt() / 100.0
            return roundedTipPercent
        }
        return parsedTipPercent
    }
}